{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "problems.serviceAccountName" . }}
  labels:
{{ include "problems.labels" . | nindent 4 }}
{{- end -}}
